name: Test GitHub Actions Run

on:
  push:
    branches:
      - testing-githubaction
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "✅ GitHub Action triggered successfully!"

      - name: Show branch
        run: echo "Branch: ${{ github.ref }}"
