image: gitpod/workspace-java-21:2025-09-22-12-51-14

github:
  prebuilds:
    # Enable for the default branch
    main: true
    # Enable for all branches
    branches: true
    # Enable for pull requests coming from this repo
    pullRequests: true
    # Enable for pull requests coming from forks
    pullRequestsFromForks: false
    # Add a check to pull requests
    addCheck: true
    # Add a "Review in Gitpod" button as a comment to pull requests
    addComment: true
    # Add a "Review in Gitpod" button to the pull request's description
    addBadge: false

tasks:
  - name: Maven Build
    # Prebuild: install dependencies and compile
    init: mvn -B -DskipTests=true install
    # Ready: just run tests to verify everything works
    command: mvn -q test && echo "✅ Workspace ready! All tests passed."

vscode:
  extensions:
    - vscjava.vscode-java-pack
