name: Build Java JAR using Maven

on:
  push:
    branches:
      - main

jobs:
  build:                # <-- only one 'build'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java (Temurin is a free JDK)
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
         java-version: '21'
         distribution: 'temurin'


      # Step 3: Build your project with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Show the JAR file output
      - name: List target directory
        run: ls -l target

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar

          jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build JAR
      - name: Build with Maven
        run: mvn clean package

      # Upload the JAR as a zip
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar

     
     
