name: Build Java JAR using Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java (Temurin is a free JDK)
      - name: Set up Java 21
        uses: actions/setup-java@v4
      with:
       java-version: '21'
       distribution: 'temurin'


      # Step 3: Build your project with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Show the JAR file output
      - name: List target directory
        run: ls -l target
